[package]
name = "edi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beryllium = "0.13.0"
gl33 = "0.2.1"
thiserror = "1.0.49"
